/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LiveRouteImport } from './routes/live'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorktreesRouteImport } from './routes/worktrees'
import { Route as ReviewSourceIdRouteImport } from './routes/review.$source.$id'
import { Route as SessionsSourceIdRouteImport } from './routes/sessions/$source/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorktreesRoute = WorktreesRouteImport.update({
  id: '/worktrees',
  path: '/worktrees',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSourceIdRoute = ReviewSourceIdRouteImport.update({
  id: '/review/$source/$id',
  path: '/review/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSourceIdRoute = SessionsSourceIdRouteImport.update({
  id: '/sessions/$source/$id',
  path: '/sessions/$source/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/worktrees': typeof WorktreesRoute
  '/review/$source/$id': typeof ReviewSourceIdRoute
  '/sessions/$source/$id': typeof SessionsSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/worktrees': typeof WorktreesRoute
  '/review/$source/$id': typeof ReviewSourceIdRoute
  '/sessions/$source/$id': typeof SessionsSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/worktrees': typeof WorktreesRoute
  '/review/$source/$id': typeof ReviewSourceIdRoute
  '/sessions/$source/$id': typeof SessionsSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/history'
    | '/inbox'
    | '/live'
    | '/settings'
    | '/worktrees'
    | '/review/$source/$id'
    | '/sessions/$source/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/history'
    | '/inbox'
    | '/live'
    | '/settings'
    | '/worktrees'
    | '/review/$source/$id'
    | '/sessions/$source/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/history'
    | '/inbox'
    | '/live'
    | '/settings'
    | '/worktrees'
    | '/review/$source/$id'
    | '/sessions/$source/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  HistoryRoute: typeof HistoryRoute
  InboxRoute: typeof InboxRoute
  LiveRoute: typeof LiveRoute
  SettingsRoute: typeof SettingsRoute
  WorktreesRoute: typeof WorktreesRoute
  ReviewSourceIdRoute: typeof ReviewSourceIdRoute
  SessionsSourceIdRoute: typeof SessionsSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worktrees': {
      id: '/worktrees'
      path: '/worktrees'
      fullPath: '/worktrees'
      preLoaderRoute: typeof WorktreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$source/$id': {
      id: '/review/$source/$id'
      path: '/review/$source/$id'
      fullPath: '/review/$source/$id'
      preLoaderRoute: typeof ReviewSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$source/$id': {
      id: '/sessions/$source/$id'
      path: '/sessions/$source/$id'
      fullPath: '/sessions/$source/$id'
      preLoaderRoute: typeof SessionsSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  HistoryRoute: HistoryRoute,
  InboxRoute: InboxRoute,
  LiveRoute: LiveRoute,
  SettingsRoute: SettingsRoute,
  WorktreesRoute: WorktreesRoute,
  ReviewSourceIdRoute: ReviewSourceIdRoute,
  SessionsSourceIdRoute: SessionsSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
