import type {
  ApiClient,
  P2Methods,
  P3Methods,
  P5ClientMethods,
  P6Methods,
  Phase4Client,
} from '@orc/api-contract';
import { vi } from 'vitest';

const unexpected = (name: string) =>
  vi.fn(async (): Promise<never> => {
    throw new Error(`unexpected api call: ${name}`);
  });

export type FakeApi = ApiClient & P2Methods & P3Methods & Phase4Client & P5ClientMethods & P6Methods;

export function createFakeApi(overrides: Partial<FakeApi> = {}): FakeApi {
  const base: FakeApi = {
    healthGet: vi.fn(async () => ({ ok: true, version: '0.0.0', uptimeS: 1 })),
    projectsList: vi.fn(async () => []),
    projectsGet: unexpected('projectsGet'),
    projectsUpdate: unexpected('projectsUpdate'),
    sessionsList: vi.fn(async () => ({ items: [], nextCursor: null })),
    sessionsGet: unexpected('sessionsGet'),
    sessionsEvents: vi.fn(async () => ({ items: [], nextSeq: null })),
    sessionsAgents: vi.fn(async () => []),
    sessionsResume: unexpected('sessionsResume'),
    sessionsPin: vi.fn(async (_source: string, _id: string, pinned: boolean) => ({ pinned })),
    sessionsLabel: vi.fn(async (_source: string, _id: string, labels: string[]) => ({ labels })),
    labelsList: vi.fn(async () => []),
    viewsList: vi.fn(async () => []),
    viewsSave: unexpected('viewsSave'),
    viewsDelete: vi.fn(async () => ({ ok: true as const })),
    ptyList: vi.fn(async () => []),
    ptyKill: vi.fn(async () => ({ ok: true as const })),
    liveList: vi.fn(async () => []),
    sessionsLaunch: unexpected('sessionsLaunch'),
    sessionsKill: unexpected('sessionsKill'),
    sessionsOpenIn: unexpected('sessionsOpenIn'),
    inboxList: vi.fn(async () => []),
    inboxDone: unexpected('inboxDone'),
    inboxSnooze: unexpected('inboxSnooze'),
    inboxReopen: unexpected('inboxReopen'),
    templatesList: vi.fn(async () => []),
    archiveStatus: unexpected('archiveStatus'),
    archiveRestore: unexpected('archiveRestore'),
    archiveSync: unexpected('archiveSync'),
    notificationsGet: unexpected('notificationsGet'),
    notificationsPut: unexpected('notificationsPut'),
    sessionsStats: unexpected('sessionsStats'),
    sessionsDeliverables: unexpected('sessionsDeliverables'),
    sessionsFiles: unexpected('sessionsFiles'),
    sessionsUsageSeries: unexpected('sessionsUsageSeries'),
    sessionsSafety: unexpected('sessionsSafety'),
    sessionsLinks: unexpected('sessionsLinks'),
    sessionsRaw: unexpected('sessionsRaw'),
    sessionsExport: unexpected('sessionsExport'),
    plansList: unexpected('plansList'),
    plansContent: unexpected('plansContent'),
    auditList: unexpected('auditList'),
    safetySecrets: unexpected('safetySecrets'),
    safetyDenyCheck: unexpected('safetyDenyCheck'),
    worktreesList: unexpected('worktreesList'),
    worktreesDiscover: unexpected('worktreesDiscover'),
    worktreesGet: unexpected('worktreesGet'),
    worktreesCreate: unexpected('worktreesCreate'),
    worktreesScript: unexpected('worktreesScript'),
    worktreesOpen: unexpected('worktreesOpen'),
    worktreesSyncPreview: unexpected('worktreesSyncPreview'),
    worktreesSync: unexpected('worktreesSync'),
    worktreesArchive: unexpected('worktreesArchive'),
    diffGet: unexpected('diffGet'),
    diffRevert: unexpected('diffRevert'),
    checkpointsList: unexpected('checkpointsList'),
    checkpointsDiff: unexpected('checkpointsDiff'),
    checkpointsCreate: unexpected('checkpointsCreate'),
    checkpointsRewind: unexpected('checkpointsRewind'),
    reviewGet: unexpected('reviewGet'),
    reviewComments: unexpected('reviewComments'),
    shipSuggest: unexpected('shipSuggest'),
    shipCommit: unexpected('shipCommit'),
    shipPush: unexpected('shipPush'),
    shipPr: unexpected('shipPr'),
    shipMerge: unexpected('shipMerge'),
    shipBackmerge: unexpected('shipBackmerge'),
    planApprove: unexpected('planApprove'),
    planReject: unexpected('planReject'),
    githubStatus: unexpected('githubStatus'),
    githubPr: unexpected('githubPr'),
    githubMine: unexpected('githubMine'),
    usageGet: unexpected('usageGet'),
    usageBudgets: unexpected('usageBudgets'),
    usageBudgetUpsert: unexpected('usageBudgetUpsert'),
    usageBudgetDelete: unexpected('usageBudgetDelete'),
    usageConcurrency: unexpected('usageConcurrency'),
    usageContext: unexpected('usageContext'),
    settingsGet: unexpected('settingsGet'),
    settingsUpdate: unexpected('settingsUpdate'),
    analyticsCost: unexpected('analyticsCost'),
    analyticsTop: unexpected('analyticsTop'),
    analyticsTools: unexpected('analyticsTools'),
    analyticsTiming: unexpected('analyticsTiming'),
    analyticsOutcomes: unexpected('analyticsOutcomes'),
    analyticsWstack: unexpected('analyticsWstack'),
    analyticsDigestLatest: unexpected('analyticsDigestLatest'),
    analyticsDigestGenerate: unexpected('analyticsDigestGenerate'),
    streamsList: unexpected('streamsList'),
    streamsRefresh: unexpected('streamsRefresh'),
    streamsGet: unexpected('streamsGet'),
    streamsLink: unexpected('streamsLink'),
    streamsUnlink: unexpected('streamsUnlink'),
    recapsGetSession: unexpected('recapsGetSession'),
    recapsRunSession: unexpected('recapsRunSession'),
    recapsGetDaily: unexpected('recapsGetDaily'),
    recapsRunDaily: unexpected('recapsRunDaily'),
    recapsSpend: unexpected('recapsSpend'),
    goalsList: unexpected('goalsList'),
    goalsGet: unexpected('goalsGet'),
    goalsSet: unexpected('goalsSet'),
    handoffsLatest: unexpected('handoffsLatest'),
    handoffsGenerate: unexpected('handoffsGenerate'),
    handoffsResumeFresh: unexpected('handoffsResumeFresh'),
    remindersList: unexpected('remindersList'),
    remindersCreate: unexpected('remindersCreate'),
    remindersCancel: unexpected('remindersCancel'),
    hooksInstallStatus: unexpected('hooksInstallStatus'),
    hooksInstall: unexpected('hooksInstall'),
    hooksStatusline: unexpected('hooksStatusline'),
    connectorsList: unexpected('connectorsList'),
    connectorsSetToken: unexpected('connectorsSetToken'),
    connectorsSetApp: unexpected('connectorsSetApp'),
    connectorsAuthorize: unexpected('connectorsAuthorize'),
    connectorsDisconnect: unexpected('connectorsDisconnect'),
    linearIssue: unexpected('linearIssue'),
    linearComment: unexpected('linearComment'),
    linearFollowUp: unexpected('linearFollowUp'),
    slackPost: unexpected('slackPost'),
    sessionsReply: unexpected('sessionsReply'),
    inboxApprove: unexpected('inboxApprove'),
    remoteStatus: unexpected('remoteStatus'),
    remoteSetConfig: unexpected('remoteSetConfig'),
    remoteCreatePairing: unexpected('remoteCreatePairing'),
    remotePair: unexpected('remotePair'),
    remoteDevices: unexpected('remoteDevices'),
    remoteRevokeDevice: unexpected('remoteRevokeDevice'),
    awayGet: unexpected('awayGet'),
    awaySet: unexpected('awaySet'),
    webauthnRegisterOptions: unexpected('webauthnRegisterOptions'),
    webauthnRegisterVerify: unexpected('webauthnRegisterVerify'),
    webauthnStepUpOptions: unexpected('webauthnStepUpOptions'),
    webauthnStepUpVerify: unexpected('webauthnStepUpVerify'),
    pushPublicKey: unexpected('pushPublicKey'),
    pushSubscribe: unexpected('pushSubscribe'),
    pushUnsubscribe: unexpected('pushUnsubscribe'),
    pushTest: unexpected('pushTest'),
    automationsList: unexpected('automationsList'),
    automationsGet: unexpected('automationsGet'),
    automationsSave: unexpected('automationsSave'),
    automationsDelete: unexpected('automationsDelete'),
    automationsSetEnabled: unexpected('automationsSetEnabled'),
    automationsRun: unexpected('automationsRun'),
    automationsRuns: unexpected('automationsRuns'),
    automationsRunGet: unexpected('automationsRunGet'),
    automationsRunLog: unexpected('automationsRunLog'),
    automationsApprove: unexpected('automationsApprove'),
    automationsReject: unexpected('automationsReject'),
    automationsRerun: unexpected('automationsRerun'),
    automationsSettingsGet: unexpected('automationsSettingsGet'),
    automationsSettings: unexpected('automationsSettings'),
    suggestionsList: unexpected('suggestionsList'),
    suggestionsRefresh: unexpected('suggestionsRefresh'),
    suggestionsAccept: unexpected('suggestionsAccept'),
    suggestionsDismiss: unexpected('suggestionsDismiss'),
    compareLaunch: unexpected('compareLaunch'),
    compareEstimate: unexpected('compareEstimate'),
    compareGet: unexpected('compareGet'),
    comparePickWinner: unexpected('comparePickWinner'),
    compareArchiveLosers: unexpected('compareArchiveLosers'),
    supervisorStatus: unexpected('supervisorStatus'),
    supervisorSettings: unexpected('supervisorSettings'),
    supervisorTargets: unexpected('supervisorTargets'),
    supervisorSetTarget: unexpected('supervisorSetTarget'),
    supervisorRules: unexpected('supervisorRules'),
    supervisorAddRule: unexpected('supervisorAddRule'),
    supervisorDeleteRule: unexpected('supervisorDeleteRule'),
    supervisorDecisions: unexpected('supervisorDecisions'),
    supervisorMarkWrong: unexpected('supervisorMarkWrong'),
    supervisorEvaluate: unexpected('supervisorEvaluate'),
    agncStatus: unexpected('agncStatus'),
    agncConnect: unexpected('agncConnect'),
    agncMessages: unexpected('agncMessages'),
    agncEvents: unexpected('agncEvents'),
    agncPrompt: unexpected('agncPrompt'),
    agncHandoff: unexpected('agncHandoff'),
    agncDisconnect: unexpected('agncDisconnect'),
  };
  return { ...base, ...overrides };
}
